### ISSUE TITLE
auro-button; redev / refactor upgrade

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/ods-button#83]
# User story

As a developer, I want to be able to work with the latest version of the WC Generator tools, so I can be more efficient.

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [x] Generate a fresh repo with the WC Generator
- [x] Port over all the Auro code
- [x] Push all new code to the same repo
- [x] Leave ODS in the dust
- [x] Update package to @alaskaairux/auro-button

> Other stories to address with this work

- [x] https://github.com/AlaskaAirlines/ods-button/issues/82 - auro-button: deliver AURO-button as stand-alone npm
- [ ] Bug: https://github.com/AlaskaAirlines/ods-button/issues/77 - Previously-disabled button is not focusable with the keyboard in IE11
- [x] https://github.com/AlaskaAirlines/ods-button/issues/74 - auro-button: Support static styles
- [x] https://github.com/AlaskaAirlines/ods-button/issues/48 - auro-button: Remove altImports support
- [x] https://github.com/AlaskaAirlines/ods-button/issues/43 - Set up for unit tests
- [ ] https://github.com/AlaskaAirlines/ods-button/issues/65 - Button + icon support

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

#### Has been tested in all browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Edge (79 +)
- [ ] Safari
- [ ] Mobile Safari
- [ ] IE11

#### Has been tested for accessibility

- [ ] Screenreader
- [ ] Axe
- [ ] Keyboard use

#### Performance

- [ ] Chrome Lighthhouse report

#### Auro component features

- [ ] README doc completed with all relative information
- [ ] API documentation created
- [ ] Bundled version tested and documented
- [ ] Examples and use case info created
- [ ] Pages added to the Auro Doc Site

## Audit

https://github.com/AlaskaAirlines/auro/issues/107
